[project]
authors = ["lanyusea <lanyusea@gmail.com>"]
channels = ["conda-forge"]
name = "day1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
run = "cargo run -- /home/phoenix/code/github/aoc2024/day1/input.txt" #no idea how to fix this F**K

[dependencies]
rust = ">=1.84.0,<1.85"
